WITH RECURSIVE ECOLI AS (
    SELECT ID,PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT A.ID, A.PARENT_ID, B.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA A
    JOIN ECOLI B
      ON A.PARENT_ID = B.ID
)
SELECT ID
FROM ECOLI
WHERE GENERATION = 3
ORDER BY ID
