-- 동일한 회원이 동일한 상품을 재구매한 데이터 -> 재구매한 회원ID(ASC)와 상품ID 출력 -> 회원ID가 같다면 상품ID 기준으로(DESC)
SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(PRODUCT_ID) >= 2
ORDER BY USER_ID ASC, PRODUCT_ID DESC