SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS A
JOIN (SELECT ANIMAL_ID
      FROM ANIMAL_OUTS 
      WHERE SEX_UPON_OUTCOME LIKE 'Neutered%' || SEX_UPON_OUTCOME LIKE 'Spayed%'
      ) B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.SEX_UPON_INTAKE LIKE 'Intact%' 

