SELECT A.REST_ID, B.REST_NAME, B.FOOD_TYPE, B.FAVORITES, B.ADDRESS, ROUND(AVG(A.REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW AS A
JOIN(
    SELECT *
    FROM REST_INFO
    WHERE ADDRESS LIKE '서울%'
    ) AS B
ON A.REST_ID = B.REST_ID
GROUP BY B.REST_ID, B.REST_NAME, B.FOOD_TYPE, B.FAVORITES, B.ADDRESS
ORDER BY SCORE DESC, B.FAVORITES DESC;
