WITH RECURSIVE ECOLI AS (

    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT B.ID, B.PARENT_ID, P.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA B
    JOIN ECOLI P
    ON B.PARENT_ID = P.ID
)

SELECT COUNT(*) AS COUNT, E.GENERATION AS GENERATION
FROM ECOLI E
LEFT JOIN ECOLI_DATA C
ON C.PARENT_ID = E.ID  
WHERE C.ID IS NULL       
GROUP BY E.GENERATION
ORDER BY E.GENERATION
