-- 7월 총 주문량과 상반기의 총 주문량을 더한 값이 큰 순서대로 상위 3개의 맛 조회
SELECT A.FLAVOR
FROM FIRST_HALF A
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL
     FROM JULY
     GROUP BY FLAVOR) B
ON A.FLAVOR = B.FLAVOR
ORDER BY (A.TOTAL_ORDER + B.JULY_TOTAL) DESC
LIMIT 3;
