-- 보호 시작일 > 입양일 -> 아이디와 이름 조회 
-- 보호 시작일 빠른순 조회 
SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_INS AS A
JOIN ANIMAL_OUTS AS B
ON A.ANIMAL_ID = B.ANIMAL_ID AND A.DATETIME > B.DATETIME
ORDER BY A.DATETIME ASC;
