-- 물고기 종류 별로 가장 큰 물고기의 ID, 물고기 이름, 길이를 출력
SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO A
JOIN FISH_NAME_INFO B
ON B.FISH_TYPE = A.FISH_TYPE
WHERE A.LENGTH =(
    SELECT MAX(A2.LENGTH)
    FROM FISH_INFO A2
    WHERE A.FISH_TYPE = A2.FISH_TYPE
)
ORDER BY A.ID ASC