-- 가격이 제일 비싼 식품의 분류, 가격, 이름을 조회 -> 과자,국, 김치, 식용유인 경우만 -> 식품 가격을 DESC
SELECT  A.CATEGORY, B.MAX_PRICE, A.PRODUCT_NAME
FROM FOOD_PRODUCT AS A
JOIN(SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자','국','김치','식용유') 
GROUP BY CATEGORY ) B
ON A.CATEGORY = B.CATEGORY AND A.PRICE = B.MAX_PRICE
ORDER BY A.PRICE DESC